### ISSUE TITLE
DevelopmentVM: VS Code not linked to accelerators repo by default

### ISSUE THREAD

**Issue by GrahamAshford** [canada-ca/accelerators_accelerateurs-azure#17]
Hi!  Accoring to the vid, the accelerators_accelerateurs-azure repo should be linked automatically into VSCode when deploying the DevelopmentVM template.  

My instance did not have it linked (blank instance of VS Code).   The Git plugin was installed however, so it wasn't too difficult to add the accelerators_accelerateurs-azure repo and open it up.

**Comment by bernardmaltais** [comment]
Hello Graham, I will investigate why that might be the case. Thank you for reporting this.

Bernard

**Comment by GrahamAshford** [comment]
Thanks Bernard.  If there is any logging or otherwise that I can supply you with I would be happy to - please let me know.

Graham

**Comment by chadif** [comment]
Hi,

I ran a fresh deployment this morning and the repo was linked in VS Code when I first opened it. I did run the InstallVSCExtensions.bat batch file beforehand so not sure if that makes a difference?

Chadi

**Comment by bernardmaltais** [comment]
I found the issue. It was a bad link to the older template. It should now be fixed. I repointed the deployment to the new github location with new deployment code. All the code got moved to github recently and this was one of the few remaining updates that apparently did not get pushed.

Thank you for bringing this issue up to me chadif. I also saw the work you started to do on your fork to parametrize the baseVM name. I like it. Do not hesitate to submit a pull request when you feel you have something stable.

Bernard

**Comment by bernardmaltais** [comment]
Also, you will want to update your fork so you make the same change to the readme.md file I did. That way you will point to your own fork when testing deployment.

**Comment by chadif** [comment]
I actually deployed the template using Azure CLI while providing the exact URI so I think that's why it worked for me! But good point on updating the URL on the readme.md

**Comment by GrahamAshford** [comment]
Thanks for the quick turnaround folks.  I re-deployed and VSCode now has the repo linked.  Closing!
