### ISSUE TITLE
msfirewall/demo-temporary-jumpbox: Template password parameter not working

### ISSUE THREAD

**Issue by chadif** [canada-ca/accelerators_accelerateurs-azure#23]
I just deployed the msfirewall/demo-temporary-jumpbox template. 
I have replaced the adminPassword paramater in the deploy-60-servers.parameters.json parameter file beforehand. 
I was not able to RDP into the jumpbox due to rejected creds. 
I have reset the password in the portal for now and was able to RDP.
Just wanted to track this issue in case it happens to other users.

Thanks

Chadi

**Comment by bernardmaltais** [comment]
Hi chadif,

When you updated the password in deploy-60-servers.parameters.json did you also create a corresponding keyvaults entry back in the demo-core-msfw-nsg\parameters\deploy-40-keyvaults.parameters.json file?

Remember that this "adminPassword": "server2016DefaultPassword", is not actually a password but rather a keyvault secrets pointer.

**Comment by bernardmaltais** [comment]
2nd option... you could also manually create the keyvault secret in the keyvault store via the azure portal and use that new secret name as the parameter in deploy-60-servers.parameters.json.

Perhaps the parameter name adminPassword should be updated to adminPasswordSecret to reflect better the keyvault connection.

We are hard at work updating the templates documentation. The server template will greatly benefit from a good documentation update. Here is an example of the new documentation: https://github.com/canada-ca/accelerators_accelerateurs-azure/tree/master/Templates/arm/ciscoasav2NIC/20190429.1

Bernard

**Comment by chadif** [comment]
ok I was not aware of that and obviously didn't change the keyvault entries, in fact keyvault was deployed separately first.

So I think the parameter's name will be a little misleading for new users, maybe we should consider a rename or additional comments in the readme or both.

**Comment by bernardmaltais** [comment]
Will make sure we make it clear in the readme.md 

Thank you for reporting. This is how we can improve on the current templates and documentation ;-)

**Comment by chadif** [comment]
Absolutely, and thanks for your great work. I will close the issue for now.
