### ISSUE TITLE
Use DSC and Chocolaty for tools setup

### ISSUE THREAD

**Issue by nschonni** [canada-ca/accelerators_accelerateurs-azure#3]
Noticed that the tools are currently hardcoded (and out of date because VSCode moves quickly). There is instructions here for using DSC and chocolaty to install stuff like Git/VS Code https://docs.microsoft.com/en-us/azure/automation/automation-dsc-cd-chocolatey

**Comment by bernardmaltais** [comment]
Thank you, Nick,

Will have to take a look at it. This would potentially save a lot of maintenance of versions down the road.

Bernard

**Comment by bernardmaltais** [comment]
OK, all done. Give it a try and let me know what you think.

**Comment by nschonni** [comment]
Since it's early on, and there aren't any forks, it might be good to rebase out those binaries to keep cloning small

**Comment by bernardmaltais** [comment]
> Since it's early on, and there aren't any forks, it might be good to rebase out those binaries to keep cloning small

Can you guide me on doing this? Not the most proficient with git ;-) Learn something new everyday ;-)

**Comment by nschonni** [comment]
You can probably ignore the TFS parts of this guide https://docs.microsoft.com/en-us/azure/devops/repos/git/remove-binaries?view=azure-devops
I'll see if there is something clearer too

**Comment by nschonni** [comment]
This might also work http://rtyley.github.io/bfg-repo-cleaner/ but I haven't used it myself before

**Comment by bernardmaltais** [comment]
OK. I think I slayed the monster. This is what I did:

```
java -jar bfg-1.13.0.jar --strip-blobs-bigger-than 2M
git reflog expire --expire=now --all
git gc --prune=now --aggressive
git push --force
```

Let me know if the large files are still in there.

**Comment by nschonni** [comment]
Think you got them looking at https://github.com/canada-ca/accelerators_accelerateurs-azure/commit/cba10bce6c50203cd7836270023643b3a231135b
There is the `plink.exe` still in there, but it i definitlty nowhere near as big as the others were.

**Comment by bernardmaltais** [comment]
Correct. plink.exe is part of the ciscoasa based deployment solution. It is needed to deploy the configuration on the CIscoASAv NVA. I need to keep that one in there.
